### ISSUE TITLE
Missing exclamation mark

### ISSUE THREAD

**Issue by mocenas** [bucharest-gold/nodejs-rest-http-secured#50]
Greeting response "Hello World!" is missing exclamation mark

**Comment by helio-frota** [comment]
@mocenas hi.

Are you using linux or Mac ?

I can't run this booster on linux (tested on fedora and ubuntu)

**Comment by mocenas** [comment]
I'm using Linux - specifically Fedora.
And I have no problem running this booster.

**Comment by helio-frota** [comment]
I can't run this is one of the errors I saw after run `oc create -f service.sso.yaml` :

![screenshot from 2018-03-01 16-33-35](https://user-images.githubusercontent.com/6443576/36893681-bc5d220c-1de7-11e8-8579-ca2296a48c6e.png)

**Comment by mocenas** [comment]
I have a problem running the SSO service on local minishift (different error but also does not work). I usually run it on online openshift cluster.

**Comment by helio-frota** [comment]
When I use this command `minishift start --memory=6144 --iso-url=centos` 
I see other error :

![screenshot from 2018-03-02 14-56-13](https://user-images.githubusercontent.com/6443576/36913891-1bde6f78-1e2a-11e8-8ccc-2aae429ce928.png)

![screenshot from 2018-03-02 14-58-26](https://user-images.githubusercontent.com/6443576/36913910-2e96d7b8-1e2a-11e8-8792-32f81af6be39.png)

**Comment by helio-frota** [comment]
@mocenas we can run it locally with an workaround
https://github.com/bucharest-gold/nodejs-rest-http-secured/issues/56#issuecomment-370484438

we need to delete that directory before the container stop or start over again to the point of the error.

**Comment by helio-frota** [comment]
better approach:

```
oc create -f service.sso.yaml ; oc volume dc/sso --add --type=emptyDir --mount-path /opt/eap/standalone/configuration/standalone_xml_history 
```

**Comment by helio-frota** [comment]
@mocenas https://github.com/bucharest-gold/nodejs-rest-http-secured/commit/c7d41bc96e9983fb1cc6c76b89a1b5a2482d7301

now running `oc create -f service.sso.yaml ` works fine locally, tested here on fedora 27.
