### ISSUE TITLE
No ID in response

### ISSUE THREAD

**Issue by mocenas** [bucharest-gold/nodejs-rest-http-secured#51]
Due to docs, the responses should contain ID of the request, it does not.

**Comment by lholmquist** [comment]
I think this might be a docs issue

**Comment by helio-frota** [comment]
Agree, seems to be a docs issue.

**Comment by lholmquist** [comment]
the other boosters do respond with an id that increments on every GET,  not sure it really makes sense though

**Comment by helio-frota** [comment]
https://github.com/snowdrop/spring-boot-http-secured-booster/blob/master/src/main/java/io/openshiftio/booster/service/GreetingController.java#L35
it is not from SSO, this is incremented.
