### ISSUE TITLE
run SSO Server locally.

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodejs-rest-http-secured#56]

**Comment by lholmquist** [comment]
I don't think this should be to hard.  it's just knowing what environment things to change.  and i think there is a "realm" script somewhere that you can import into your local keycloak,  let me look for that

**Comment by helio-frota** [comment]
I did a workaround for now, to be able to make some progress on the other issues:

![screenshot from 2018-03-05 13-47-51](https://user-images.githubusercontent.com/6443576/36987818-06f95e8e-207c-11e8-8aa4-4ce8061147c5.png)

![screenshot from 2018-03-05 13-48-32](https://user-images.githubusercontent.com/6443576/36987829-0b3b812a-207c-11e8-8f9e-0005abe67ae6.png)

**Comment by helio-frota** [comment]
Closing for now.
Since we can run it locally.
